google.maps.__gjsload__('geometry', function(_){var qr=function(a,b){return Math.abs(_.wc(b-a,-180,180))},rr=function(a,b,c,d,e){if(!d){c=qr(a.lng(),c)/qr(a.lng(),b.lng());if(!e)return e=Math.sin(_.Pb(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Pb(b.lat())),_.Qb(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.N(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Pb(a.lat());a=_.Pb(a.lng());d=_.Pb(b.lat());b=_.Pb(b.lng());c=_.Pb(c);return _.wc(_.Qb(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},sr=_.l(),tr={containsLocation:function(a,b){var c=_.wc(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var m=e.getAt(h),p=0,q=m.getLength();p<q;++p){var t=m.getAt(p),v=m.getAt((p+1)%q),u=_.wc(t.lng(),-180,180),w=_.wc(v.lng(),-180,180),y=Math.max(u,w);u=Math.min(u,w);(180<y-u?c>=y||c<u:
c<y&&c>=u)&&rr(t,v,c,d,f)<a.lat()&&(g=!g)}return g||tr.isLocationOnEdge(a,b)}};_.Xa("PolyGeometry.containsLocation",tr.containsLocation);
tr.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.wc(a.lng(),-180,180),e=b instanceof _.$g,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var m=g.getAt(h),p=m.getLength(),q=e?p:p-1,t=0;t<q;++t){var v=m.getAt(t),u=m.getAt((t+1)%p),w=_.wc(v.lng(),-180,180),y=_.wc(u.lng(),-180,180),B=Math.max(w,y),D=Math.min(w,y);if(w=1E-9>=Math.abs(_.wc(w-y,-180,180))&&(Math.abs(_.wc(w-d,-180,180))<=c||Math.abs(_.wc(y-d,-180,180))<=
c)){w=a.lat();y=Math.min(v.lat(),u.lat())-c;var F=Math.max(v.lat(),u.lat())+c;w=w>=y&&w<=F}if(w)return!0;if(180<B-D?d+c>=B||d-c<=D:d+c>=D&&d-c<=B)if(v=rr(v,u,d,f,b),Math.abs(v-a.lat())<c)return!0}return!1};_.Xa("PolyGeometry.isLocationOnEdge",tr.isLocationOnEdge);var ur={computeHeading:function(a,b){var c=_.dd(a),d=_.ed(a);a=_.dd(b);b=_.ed(b)-d;return _.wc(_.Qb(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Xa("Spherical.computeHeading",ur.computeHeading);
ur.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.Pb(c);var e=_.dd(a);a=_.ed(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.P(_.Qb(Math.asin(g)),_.Qb(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Xa("Spherical.computeOffset",ur.computeOffset);
ur.computeOffsetOrigin=function(a,b,c,d){c=_.Pb(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.dd(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.ed(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.P(_.Qb(g),_.Qb(a))};
_.Xa("Spherical.computeOffsetOrigin",ur.computeOffsetOrigin);ur.interpolate=function(a,b,c){var d=_.dd(a),e=_.ed(a),f=_.dd(b),g=_.ed(b),h=Math.cos(d),k=Math.cos(f);b=ur.nf(a,b);var m=Math.sin(b);if(1E-6>m)return new _.P(a.lat(),a.lng());a=Math.sin((1-c)*b)/m;c=Math.sin(c*b)/m;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.P(_.Qb(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Qb(Math.atan2(e,b)))};_.Xa("Spherical.interpolate",ur.interpolate);
ur.nf=function(a,b){var c=_.dd(a);a=_.ed(a);var d=_.dd(b);b=_.ed(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};ur.computeDistanceBetween=function(a,b,c){c=c||6378137;return ur.nf(a,b)*c};_.Xa("Spherical.computeDistanceBetween",ur.computeDistanceBetween);ur.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.T&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=ur.computeDistanceBetween(a[d],a[d+1],b);return c};
_.Xa("Spherical.computeLength",ur.computeLength);ur.computeArea=function(a,b){return Math.abs(ur.computeSignedArea(a,b))};_.Xa("Spherical.computeArea",ur.computeArea);ur.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.T&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=ur.Hj(c,a[e],a[e+1]);return d*b*b};_.Xa("Spherical.computeSignedArea",ur.computeSignedArea);ur.Hj=function(a,b,c){return ur.Ij(a,b,c)*ur.Dk(a,b,c)};
ur.Ij=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=ur.nf(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
ur.Dk=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.dd(d);d=_.ed(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var vr={decodePath:function(a){for(var b=_.J(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var m=a.charCodeAt(d++)-63-1;h+=m<<k;k+=5}while(31<=m);e+=h&1?~(h>>1):h>>1;h=1;k=0;do m=a.charCodeAt(d++)-63-1,h+=m<<k,k+=5;while(31<=m);f+=h&1?~(h>>1):h>>1;c[g]=new _.P(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Xa("PolylineCodec.decodePath",vr.decodePath);
vr.encodePath=function(a){a instanceof _.T&&(a=a.getArray());return vr.Pl(a,function(a){return[Math.round(1E5*a.lat()),Math.round(1E5*a.lng())]})};_.Xa("PolylineCodec.encodePath",vr.encodePath);vr.Pl=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.J(a);f<g;++f)e=b?b(a[f]):a[f],vr.Th(e[0]-d[0],c),vr.Th(e[1]-d[1],c),d=e;return c.join("")};vr.Th=function(a,b){vr.Ql(0>a?~(a<<1):a<<1,b)};vr.Ql=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.x.google.maps.geometry={encoding:vr,spherical:ur,poly:tr};_.n=sr.prototype;_.n.decodePath=vr.decodePath;_.n.encodePath=vr.encodePath;_.n.computeDistanceBetween=ur.computeDistanceBetween;_.n.interpolate=ur.interpolate;_.n.computeHeading=ur.computeHeading;_.n.computeOffset=ur.computeOffset;_.n.computeOffsetOrigin=ur.computeOffsetOrigin;_.Ge("geometry",new sr);});
